# This is the configuration file for Roentgenium.
# Unless stated, the default values should be good enough.


[bot]
name = "Roentgenium"
# The name of the bot. This doesn't need to be the same as the account name.

id = "rontgen"
# The internal ID of the bot. 
# This is used for selecting supported commands.

all_topics = true
# If true, Roentgenium will respond to pings no matter what topic it is posted at.

ignore_list = [
    "Rontgen"
]
# A list of usernames that Roentgenium will ignore. This could be a bot or someone you really hate.


[bot.periods]
# How many seconds waiting...
process_loop = 60
# ...to parse and process alerts.

publish_loop = 60
# ...to post messages in the outbox.

no_publish_loop = 1
# ...to wait for messages in the outbox when it is empty.

siggy_loop = 900  # 15 mins
# ...to update the bot's signature.

scraping_loop = 600  # 10 mins
# ... to scrape the website for some commands that need it.


[bot.strings]
tagline = "A bot for the TBGs, round 2."
# The bot's tagline, displayed in its signature.

offline = "Currently offline."
# The message in the bot's signature that's displayed when it's offline. 

online = "Currently online. ([i]not guaranteed[/i])"
# The message in the bot's signature that's displayed when it's online.
# It's possible that the bot cannot update the signature due to a crash or any mode of failure,
# therefore it is recommended to mention here that the bot might be offline.

on_error = "While parsing that command, an error occured:"
# The message used when the bot encounters an error while parsing a command.

no_output = "[i]Command is successfully executed, but did not provide any output.[/i]"
# The message used when a command is parsed correctly, but does not provide any output.

footer = """
[font=Noto Sans](◕◡◕)[/font]
Hi! I'm Clicky. Currently My Creator used my account for Roentgenium, an up-and-coming Nihonium fork for SMF.
Once Roentgenium gone gold, she will have their own TBG account. Stay tuned!"""
# The message added in the bot's signature's footer. This could be used to give a persistent message.
# Set to blank if not needed.


[bot.auth]
# Authentication data. Fill these with your account's credentials.
username = "Clicky"
# password = "its_a_secret"
# Alternatively, the password can still be stored in pass.txt
# This is useful if you want to publish your bot to some place like GitHub.


[topics]
# A table of topics. The keys are topic IDs.
[topics.170]
types = ["tbg", "hub"]
# The tags of this topic.

first_post = 2012-12-02 00:05:09+07:00
# The time when the first post is made.

# exclusive_commands = ["rolladice", "rolldice"]
# Exclusive commands that work 
